### ISSUE TITLE
All minimized code

### ISSUE THREAD

**Issue by CrazyPython** [emotionLoop/paGen#1]
Minimized code belongs in releases, not the source directory. Think of magnification as "building" the source. This makes it much harder for contributors and security people to help you.

**Comment by BrunoBernardino** [comment]
What have you digged up! The source code's in https://github.com/emotionLoop/paGen/blob/master/code/paGen/popup.coffee and you're welcome to build an alternative to this.

**Comment by CrazyPython** [comment]
@BrunoBernardino popup.js?
